-- Meridian Global Logistics — synthetic corpus schema.
-- Generated by `meridian-seed`; do not edit by hand.

DROP TABLE IF EXISTS carrier_scorecard;
DROP TABLE IF EXISTS project_task;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS exchange_rate;
DROP TABLE IF EXISTS fuel_price;
DROP TABLE IF EXISTS shipment_charge;
DROP TABLE IF EXISTS tracking_event;
DROP TABLE IF EXISTS shipment_leg;
DROP TABLE IF EXISTS shipment;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS invoice_line;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS order_line;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS customer_contact;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS vehicle;
DROP TABLE IF EXISTS carrier;
DROP TABLE IF EXISTS facility;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS charge_type;
DROP TABLE IF EXISTS fuel_type;
DROP TABLE IF EXISTS payment_status;
DROP TABLE IF EXISTS shipment_status;
DROP TABLE IF EXISTS order_status;
DROP TABLE IF EXISTS service_level;
DROP TABLE IF EXISTS shipment_mode;
DROP TABLE IF EXISTS incoterm;
DROP TABLE IF EXISTS unit_of_measure;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS industry;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS province;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS currency;
DROP TABLE IF EXISTS region;

CREATE TABLE region (
  region_id INTEGER PRIMARY KEY,
  code VARCHAR(8) NOT NULL,
  name VARCHAR(40) NOT NULL
);

CREATE TABLE currency (
  currency_code VARCHAR(3) PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  symbol VARCHAR(8) NOT NULL,
  decimal_places INTEGER NOT NULL
);

CREATE TABLE country (
  country_id INTEGER PRIMARY KEY,
  region_id INTEGER NOT NULL,
  iso2 VARCHAR(2) NOT NULL,
  iso3 VARCHAR(3) NOT NULL,
  name VARCHAR(60) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  FOREIGN KEY (region_id) REFERENCES region (region_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE province (
  province_id INTEGER PRIMARY KEY,
  country_id INTEGER NOT NULL,
  code VARCHAR(6) NOT NULL,
  name VARCHAR(60) NOT NULL,
  FOREIGN KEY (country_id) REFERENCES country (country_id)
);

CREATE TABLE city (
  city_id INTEGER PRIMARY KEY,
  province_id INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  latitude NUMERIC(9,6) NOT NULL,
  longitude NUMERIC(9,6) NOT NULL,
  population INTEGER NOT NULL,
  FOREIGN KEY (province_id) REFERENCES province (province_id)
);

CREATE TABLE industry (
  industry_id INTEGER PRIMARY KEY,
  name VARCHAR(60) NOT NULL
);

CREATE TABLE product_category (
  category_id INTEGER PRIMARY KEY,
  parent_id INTEGER,
  name VARCHAR(60) NOT NULL,
  depth INTEGER NOT NULL,
  FOREIGN KEY (parent_id) REFERENCES product_category (category_id)
);

CREATE TABLE unit_of_measure (
  uom_id INTEGER PRIMARY KEY,
  code VARCHAR(6) NOT NULL,
  name VARCHAR(40) NOT NULL
);

CREATE TABLE incoterm (
  incoterm_id INTEGER PRIMARY KEY,
  code VARCHAR(4) NOT NULL,
  name VARCHAR(40) NOT NULL
);

CREATE TABLE shipment_mode (
  mode_id INTEGER PRIMARY KEY,
  code VARCHAR(6) NOT NULL,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE service_level (
  level_id INTEGER PRIMARY KEY,
  code VARCHAR(6) NOT NULL,
  name VARCHAR(20) NOT NULL,
  target_transit_days INTEGER NOT NULL
);

CREATE TABLE order_status (
  id INTEGER PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(30) NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE shipment_status (
  id INTEGER PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(30) NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE payment_status (
  id INTEGER PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(30) NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE fuel_type (
  fuel_id INTEGER PRIMARY KEY,
  code VARCHAR(6) NOT NULL,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE charge_type (
  charge_id INTEGER PRIMARY KEY,
  code VARCHAR(6) NOT NULL,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE department (
  department_id INTEGER PRIMARY KEY,
  parent_id INTEGER,
  name VARCHAR(60) NOT NULL,
  FOREIGN KEY (parent_id) REFERENCES department (department_id)
);

CREATE TABLE employee (
  employee_id INTEGER PRIMARY KEY,
  department_id INTEGER NOT NULL,
  manager_id INTEGER,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  title VARCHAR(40) NOT NULL,
  hire_date DATE NOT NULL,
  salary NUMERIC(12,2) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  region_id INTEGER NOT NULL,
  photo BYTEA,
  is_active BOOLEAN NOT NULL,
  FOREIGN KEY (department_id) REFERENCES department (department_id),
  FOREIGN KEY (manager_id) REFERENCES employee (employee_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
  FOREIGN KEY (region_id) REFERENCES region (region_id)
);

CREATE TABLE facility (
  facility_id INTEGER PRIMARY KEY,
  city_id INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(60) NOT NULL,
  capacity_m3 NUMERIC(12,2) NOT NULL,
  opened_date DATE NOT NULL,
  image BYTEA,
  FOREIGN KEY (city_id) REFERENCES city (city_id)
);

CREATE TABLE carrier (
  carrier_id INTEGER PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  primary_mode_id INTEGER NOT NULL,
  scac VARCHAR(4) NOT NULL,
  is_own_fleet BOOLEAN NOT NULL,
  logo BYTEA,
  FOREIGN KEY (primary_mode_id) REFERENCES shipment_mode (mode_id)
);

CREATE TABLE vehicle (
  vehicle_id INTEGER PRIMARY KEY,
  carrier_id INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  registration VARCHAR(12) NOT NULL,
  capacity_kg NUMERIC(12,2) NOT NULL,
  capacity_m3 NUMERIC(12,2) NOT NULL,
  model_year INTEGER NOT NULL,
  FOREIGN KEY (carrier_id) REFERENCES carrier (carrier_id)
);

CREATE TABLE supplier (
  supplier_id INTEGER PRIMARY KEY,
  city_id INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  rating NUMERIC(3,2) NOT NULL,
  since_date DATE NOT NULL,
  logo BYTEA,
  FOREIGN KEY (city_id) REFERENCES city (city_id)
);

CREATE TABLE product (
  product_id INTEGER PRIMARY KEY,
  category_id INTEGER NOT NULL,
  supplier_id INTEGER NOT NULL,
  uom_id INTEGER NOT NULL,
  sku VARCHAR(20) NOT NULL,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(400),
  unit_price NUMERIC(12,2) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  weight_kg NUMERIC(12,3) NOT NULL,
  volume_m3 NUMERIC(12,4) NOT NULL,
  hs_code VARCHAR(12),
  is_hazardous BOOLEAN NOT NULL,
  is_active BOOLEAN NOT NULL,
  image BYTEA,
  FOREIGN KEY (category_id) REFERENCES product_category (category_id),
  FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id),
  FOREIGN KEY (uom_id) REFERENCES unit_of_measure (uom_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE customer (
  customer_id INTEGER PRIMARY KEY,
  city_id INTEGER NOT NULL,
  industry_id INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  account_code VARCHAR(16) NOT NULL,
  credit_limit NUMERIC(14,2) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  since_date DATE NOT NULL,
  sales_rep_id INTEGER NOT NULL,
  tier VARCHAR(16) NOT NULL,
  is_active BOOLEAN NOT NULL,
  logo BYTEA,
  FOREIGN KEY (city_id) REFERENCES city (city_id),
  FOREIGN KEY (industry_id) REFERENCES industry (industry_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
  FOREIGN KEY (sales_rep_id) REFERENCES employee (employee_id)
);

CREATE TABLE customer_contact (
  contact_id INTEGER PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  email VARCHAR(80) NOT NULL,
  phone VARCHAR(24) NOT NULL,
  role VARCHAR(30) NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

CREATE TABLE sales_order (
  order_id INTEGER PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  order_date DATE NOT NULL,
  required_date DATE NOT NULL,
  status_id INTEGER NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  sales_rep_id INTEGER NOT NULL,
  ship_to_city_id INTEGER NOT NULL,
  incoterm_id INTEGER NOT NULL,
  total_amount NUMERIC(14,2) NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
  FOREIGN KEY (status_id) REFERENCES order_status (id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
  FOREIGN KEY (sales_rep_id) REFERENCES employee (employee_id),
  FOREIGN KEY (ship_to_city_id) REFERENCES city (city_id),
  FOREIGN KEY (incoterm_id) REFERENCES incoterm (incoterm_id)
);

CREATE TABLE order_line (
  order_line_id BIGINT PRIMARY KEY,
  order_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  discount_pct NUMERIC(6,3) NOT NULL,
  line_amount NUMERIC(14,2) NOT NULL,
  FOREIGN KEY (order_id) REFERENCES sales_order (order_id),
  FOREIGN KEY (product_id) REFERENCES product (product_id)
);

CREATE TABLE invoice (
  invoice_id INTEGER PRIMARY KEY,
  order_id INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  amount_net NUMERIC(14,2) NOT NULL,
  tax_amount NUMERIC(14,2) NOT NULL,
  amount_gross NUMERIC(14,2) NOT NULL,
  status_id INTEGER NOT NULL,
  FOREIGN KEY (order_id) REFERENCES sales_order (order_id),
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
  FOREIGN KEY (status_id) REFERENCES payment_status (id)
);

CREATE TABLE invoice_line (
  invoice_line_id BIGINT PRIMARY KEY,
  invoice_id INTEGER NOT NULL,
  order_line_id INTEGER NOT NULL,
  amount NUMERIC(14,2) NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoice (invoice_id),
  FOREIGN KEY (order_line_id) REFERENCES order_line (order_line_id)
);

CREATE TABLE payment (
  payment_id INTEGER PRIMARY KEY,
  invoice_id INTEGER NOT NULL,
  payment_date DATE NOT NULL,
  amount NUMERIC(14,2) NOT NULL,
  method VARCHAR(24) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoice (invoice_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE shipment (
  shipment_id INTEGER PRIMARY KEY,
  order_id INTEGER NOT NULL,
  carrier_id INTEGER NOT NULL,
  origin_facility_id INTEGER NOT NULL,
  dest_facility_id INTEGER NOT NULL,
  mode_id INTEGER NOT NULL,
  service_level_id INTEGER NOT NULL,
  status_id INTEGER NOT NULL,
  booked_date DATE NOT NULL,
  planned_pickup DATE NOT NULL,
  actual_pickup DATE NOT NULL,
  planned_delivery DATE NOT NULL,
  actual_delivery DATE,
  weight_kg NUMERIC(12,2) NOT NULL,
  volume_m3 NUMERIC(12,3) NOT NULL,
  chargeable_weight NUMERIC(12,2) NOT NULL,
  freight_cost NUMERIC(14,2) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  distance_km NUMERIC(10,2) NOT NULL,
  FOREIGN KEY (order_id) REFERENCES sales_order (order_id),
  FOREIGN KEY (carrier_id) REFERENCES carrier (carrier_id),
  FOREIGN KEY (origin_facility_id) REFERENCES facility (facility_id),
  FOREIGN KEY (dest_facility_id) REFERENCES facility (facility_id),
  FOREIGN KEY (mode_id) REFERENCES shipment_mode (mode_id),
  FOREIGN KEY (service_level_id) REFERENCES service_level (level_id),
  FOREIGN KEY (status_id) REFERENCES shipment_status (id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE shipment_leg (
  leg_id BIGINT PRIMARY KEY,
  shipment_id INTEGER NOT NULL,
  sequence INTEGER NOT NULL,
  from_facility_id INTEGER NOT NULL,
  to_facility_id INTEGER NOT NULL,
  mode_id INTEGER NOT NULL,
  carrier_id INTEGER NOT NULL,
  vehicle_id INTEGER NOT NULL,
  planned_depart DATE NOT NULL,
  actual_depart DATE NOT NULL,
  planned_arrive DATE NOT NULL,
  actual_arrive DATE NOT NULL,
  distance_km NUMERIC(10,2) NOT NULL,
  leg_cost NUMERIC(14,2) NOT NULL,
  FOREIGN KEY (shipment_id) REFERENCES shipment (shipment_id),
  FOREIGN KEY (from_facility_id) REFERENCES facility (facility_id),
  FOREIGN KEY (to_facility_id) REFERENCES facility (facility_id),
  FOREIGN KEY (mode_id) REFERENCES shipment_mode (mode_id),
  FOREIGN KEY (carrier_id) REFERENCES carrier (carrier_id),
  FOREIGN KEY (vehicle_id) REFERENCES vehicle (vehicle_id)
);

CREATE TABLE tracking_event (
  event_id BIGINT PRIMARY KEY,
  shipment_id INTEGER NOT NULL,
  leg_id INTEGER NOT NULL,
  event_time TIMESTAMP NOT NULL,
  event_type VARCHAR(30) NOT NULL,
  facility_id INTEGER NOT NULL,
  city_id INTEGER NOT NULL,
  temperature_c NUMERIC(5,2),
  notes VARCHAR(200),
  FOREIGN KEY (shipment_id) REFERENCES shipment (shipment_id),
  FOREIGN KEY (leg_id) REFERENCES shipment_leg (leg_id),
  FOREIGN KEY (facility_id) REFERENCES facility (facility_id),
  FOREIGN KEY (city_id) REFERENCES city (city_id)
);

CREATE TABLE shipment_charge (
  charge_id BIGINT PRIMARY KEY,
  shipment_id INTEGER NOT NULL,
  charge_type_id INTEGER NOT NULL,
  amount NUMERIC(14,2) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  FOREIGN KEY (shipment_id) REFERENCES shipment (shipment_id),
  FOREIGN KEY (charge_type_id) REFERENCES charge_type (charge_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE fuel_price (
  fuel_id INTEGER NOT NULL,
  price_date DATE NOT NULL,
  open NUMERIC(10,4) NOT NULL,
  high NUMERIC(10,4) NOT NULL,
  low NUMERIC(10,4) NOT NULL,
  close NUMERIC(10,4) NOT NULL,
  volume BIGINT NOT NULL,
  PRIMARY KEY (fuel_id, price_date),
  FOREIGN KEY (fuel_id) REFERENCES fuel_type (fuel_id)
);

CREATE TABLE exchange_rate (
  currency_code VARCHAR(3) NOT NULL,
  rate_date DATE NOT NULL,
  rate_to_usd NUMERIC(14,6) NOT NULL,
  PRIMARY KEY (currency_code, rate_date),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE project (
  project_id INTEGER PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  facility_id INTEGER NOT NULL,
  region_id INTEGER NOT NULL,
  project_manager_id INTEGER NOT NULL,
  start_date DATE NOT NULL,
  planned_end_date DATE NOT NULL,
  actual_end_date DATE,
  budget NUMERIC(16,2) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  status_id INTEGER NOT NULL,
  FOREIGN KEY (facility_id) REFERENCES facility (facility_id),
  FOREIGN KEY (region_id) REFERENCES region (region_id),
  FOREIGN KEY (project_manager_id) REFERENCES employee (employee_id),
  FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);

CREATE TABLE project_task (
  task_id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  name VARCHAR(80) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  pct_complete NUMERIC(5,2) NOT NULL,
  predecessor_task_id INTEGER,
  assigned_to INTEGER NOT NULL,
  phase VARCHAR(20) NOT NULL,
  FOREIGN KEY (project_id) REFERENCES project (project_id),
  FOREIGN KEY (predecessor_task_id) REFERENCES project_task (task_id),
  FOREIGN KEY (assigned_to) REFERENCES employee (employee_id)
);

CREATE TABLE carrier_scorecard (
  scorecard_id INTEGER PRIMARY KEY,
  carrier_id INTEGER NOT NULL,
  period_month DATE NOT NULL,
  on_time_pct NUMERIC(5,2) NOT NULL,
  damage_rate NUMERIC(6,4) NOT NULL,
  cost_index NUMERIC(6,3) NOT NULL,
  capacity_utilization NUMERIC(5,2) NOT NULL,
  claims_count INTEGER NOT NULL,
  FOREIGN KEY (carrier_id) REFERENCES carrier (carrier_id)
);

