// Hand-maintained type table for the formula builtins — `include!`d into `types.rs` (which owns the
// `ReturnRule`/`StrLenRule`/`Sig` types the rows are built from). Each row states, for one builtin
// name, how its result kind follows from its arguments, how wide a string result may get, and how
// many arguments it accepts. Add or adjust a row by hand when a builtin gains a type or signature
// (see docs/formula-engine/03-builtins.md); no generator produces this file.
//
// Names are lowercased and the table is sorted by name for binary search. A name that spells the
// same builtin as another (`Truncate`/`Fix`, `ToText`/`CStr`, `Today`/`CurrentDate`) gets its own
// row carrying the same rules.

use ReturnRule as R;
use Sig as A;
use StrLenRule as L;

/// The rules for one builtin: return-type rule, string-length rule, argument-count signature.
pub(super) type Rules = (ReturnRule, StrLenRule, Sig);

/// Lowercased builtin/function name -> its [`Rules`]. Sorted by name for binary search.
pub(super) static BUILTINS: &[(&str, ReturnRule, StrLenRule, Sig)] = &[
    ("abs", R::CopyArg, L::Unbounded, A::Exact(1)),
    ("accrint", R::Fixed(1), L::Unbounded, A::Any),
    ("accrintm", R::Fixed(1), L::Unbounded, A::Any),
    ("aged0to30days", R::Fixed(11), L::Unbounded, A::Any),
    ("aged31to60days", R::Fixed(11), L::Unbounded, A::Any),
    ("aged61to90days", R::Fixed(11), L::Unbounded, A::Any),
    ("alertmessage", R::Complex, L::Unbounded, A::Any),
    ("alldatesfromtoday", R::Fixed(11), L::Unbounded, A::Any),
    ("alldatesfromtomorrow", R::Fixed(11), L::Unbounded, A::Any),
    ("alldatestotoday", R::Fixed(11), L::Unbounded, A::Any),
    ("alldatestoyesterday", R::Fixed(11), L::Unbounded, A::Any),
    ("amordegrc", R::Fixed(1), L::Unbounded, A::Any),
    ("amorlinc", R::Fixed(1), L::Unbounded, A::Any),
    ("asc", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("ascw", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("atn", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("average", R::AggNumeric, L::Unbounded, A::AtLeast(1)),
    ("beforereadingrecords", R::Fixed(1), L::Unbounded, A::Any),
    ("calendar1sthalf", R::Fixed(11), L::Unbounded, A::Any),
    ("calendar1stqtr", R::Fixed(11), L::Unbounded, A::Any),
    ("calendar2ndhalf", R::Fixed(11), L::Unbounded, A::Any),
    ("calendar2ndqtr", R::Fixed(11), L::Unbounded, A::Any),
    ("calendar3rdqtr", R::Fixed(11), L::Unbounded, A::Any),
    ("calendar4thqtr", R::Fixed(11), L::Unbounded, A::Any),
    ("cbool", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("ccur", R::Fixed(2), L::Unbounded, A::Exact(1)),
    ("cdate", R::Fixed(4), L::Unbounded, A::Range(1, 3)),
    ("cdatetime", R::Fixed(6), L::Unbounded, A::Range(1, 6)),
    ("cdbl", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("ceiling", R::CopyArg, L::Unbounded, A::Range(1, 2)),
    ("choose", R::Choose, L::BranchMax, A::AtLeast(2)),
    ("chr", R::Fixed(7), L::Const(6), A::Exact(1)),
    ("chrw", R::Fixed(7), L::Const(6), A::Exact(1)),
    ("color", R::Fixed(1), L::Unbounded, A::Exact(3)),
    ("contentlocale", R::Complex, L::Unbounded, A::Any),
    ("correlation", R::Complex, L::Unbounded, A::Any),
    ("cos", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("count", R::Fixed(1), L::Unbounded, A::AtLeast(1)),
    ("counthierarchicalchildren", R::Fixed(1), L::Unbounded, A::Any),
    ("coupdaybs", R::Fixed(1), L::Unbounded, A::Any),
    ("coupdays", R::Fixed(1), L::Unbounded, A::Any),
    ("coupdaysnc", R::Fixed(1), L::Unbounded, A::Any),
    ("coupncd", R::Complex, L::Unbounded, A::Any),
    ("coupnum", R::Complex, L::Unbounded, A::Any),
    ("couppcd", R::Complex, L::Unbounded, A::Any),
    ("covariance", R::Complex, L::Unbounded, A::Any),
    ("crampmafter", R::Fixed(1), L::Unbounded, A::Any),
    ("crampmbefore", R::Fixed(1), L::Unbounded, A::Any),
    ("craqua", R::Fixed(1), L::Unbounded, A::Any),
    ("crascendingorder", R::Fixed(1), L::Unbounded, A::Any),
    ("crblack", R::Fixed(1), L::Unbounded, A::Any),
    ("crblue", R::Fixed(1), L::Unbounded, A::Any),
    ("crbold", R::Fixed(1), L::Unbounded, A::Any),
    ("crbolditalic", R::Fixed(1), L::Unbounded, A::Any),
    ("crbottomaligned", R::Fixed(1), L::Unbounded, A::Any),
    ("crbracketednegatives", R::Fixed(1), L::Unbounded, A::Any),
    ("crcenteredhorizontally", R::Fixed(1), L::Unbounded, A::Any),
    ("crcenteredvertically", R::Fixed(1), L::Unbounded, A::Any),
    ("crcustom", R::Fixed(1), L::Unbounded, A::Any),
    ("crdashedline", R::Fixed(1), L::Unbounded, A::Any),
    ("crdateonly", R::Fixed(1), L::Unbounded, A::Any),
    ("crdatethentime", R::Fixed(1), L::Unbounded, A::Any),
    ("crdaymonthyear", R::Fixed(1), L::Unbounded, A::Any),
    ("crdayofweekinfwparentheses", R::Fixed(1), L::Unbounded, A::Any),
    ("crdayofweekinfwsquarebrackets", R::Fixed(1), L::Unbounded, A::Any),
    ("crdayofweekinparentheses", R::Fixed(1), L::Unbounded, A::Any),
    ("crdayofweekinsquarebrackets", R::Fixed(1), L::Unbounded, A::Any),
    ("crdayofweeknotenclosed", R::Fixed(1), L::Unbounded, A::Any),
    ("crdefaulthoraligned", R::Fixed(1), L::Unbounded, A::Any),
    ("crdefaultorientation", R::Fixed(1), L::Unbounded, A::Any),
    ("crdefaultveraligned", R::Fixed(1), L::Unbounded, A::Any),
    ("crdescendingorder", R::Fixed(1), L::Unbounded, A::Any),
    ("crdottedline", R::Fixed(1), L::Unbounded, A::Any),
    ("crdoubleline", R::Fixed(1), L::Unbounded, A::Any),
    ("crfirstfourdays", R::Fixed(1), L::Unbounded, A::Any),
    ("crfirstfullweek", R::Fixed(1), L::Unbounded, A::Any),
    ("crfirstjan1", R::Fixed(1), L::Unbounded, A::Any),
    ("crfixedcurrencysymbol", R::Fixed(1), L::Unbounded, A::Any),
    ("crfloatingcurrencysymbol", R::Fixed(1), L::Unbounded, A::Any),
    ("crfriday", R::Fixed(1), L::Unbounded, A::Any),
    ("crfuchsia", R::Fixed(1), L::Unbounded, A::Any),
    ("crgray", R::Fixed(1), L::Unbounded, A::Any),
    ("crgreen", R::Fixed(1), L::Unbounded, A::Any),
    ("crgregoriancalendar", R::Fixed(1), L::Unbounded, A::Any),
    ("crgregorianenglishcalendar", R::Fixed(1), L::Unbounded, A::Any),
    ("crhairline", R::Fixed(1), L::Unbounded, A::Any),
    ("crhalfpointline", R::Fixed(1), L::Unbounded, A::Any),
    ("crhtmltext", R::Fixed(1), L::Unbounded, A::Any),
    ("critalic", R::Fixed(1), L::Unbounded, A::Any),
    ("crjapanesecalendar", R::Fixed(1), L::Unbounded, A::Any),
    ("crjustified", R::Fixed(1), L::Unbounded, A::Any),
    ("crlandscape", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingcurrencyinsidenegative", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingcurrencyoutsidenegative", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingdayofweek", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingminus", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingzeroday", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingzerohour", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingzerominute", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingzeromonth", R::Fixed(1), L::Unbounded, A::Any),
    ("crleadingzerosecond", R::Fixed(1), L::Unbounded, A::Any),
    ("crleftaligned", R::Fixed(1), L::Unbounded, A::Any),
    ("crlefttorighttextreadingorder", R::Fixed(1), L::Unbounded, A::Any),
    ("crlime", R::Fixed(1), L::Unbounded, A::Any),
    ("crlongdayofweek", R::Fixed(1), L::Unbounded, A::Any),
    ("crlongera", R::Fixed(1), L::Unbounded, A::Any),
    ("crlongleadingday", R::Fixed(1), L::Unbounded, A::Any),
    ("crlongmonth", R::Fixed(1), L::Unbounded, A::Any),
    ("crlongyear", R::Fixed(1), L::Unbounded, A::Any),
    ("crmaroon", R::Fixed(1), L::Unbounded, A::Any),
    ("crmonday", R::Fixed(1), L::Unbounded, A::Any),
    ("crmonthdayyear", R::Fixed(1), L::Unbounded, A::Any),
    ("crnavy", R::Fixed(1), L::Unbounded, A::Any),
    ("crnocolor", R::Fixed(1), L::Unbounded, A::Any),
    ("crnocurrencysymbol", R::Fixed(1), L::Unbounded, A::Any),
    ("crnoday", R::Fixed(1), L::Unbounded, A::Any),
    ("crnodayofweek", R::Fixed(1), L::Unbounded, A::Any),
    ("crnoera", R::Fixed(1), L::Unbounded, A::Any),
    ("crnohour", R::Fixed(1), L::Unbounded, A::Any),
    ("crnoleadingday", R::Fixed(1), L::Unbounded, A::Any),
    ("crnoline", R::Fixed(1), L::Unbounded, A::Any),
    ("crnominute", R::Fixed(1), L::Unbounded, A::Any),
    ("crnomonth", R::Fixed(1), L::Unbounded, A::Any),
    ("crnonegativesign", R::Fixed(1), L::Unbounded, A::Any),
    ("crnosecond", R::Fixed(1), L::Unbounded, A::Any),
    ("crnoyear", R::Fixed(1), L::Unbounded, A::Any),
    ("crnumericday", R::Fixed(1), L::Unbounded, A::Any),
    ("crnumerichour", R::Fixed(1), L::Unbounded, A::Any),
    ("crnumericminute", R::Fixed(1), L::Unbounded, A::Any),
    ("crnumericmonth", R::Fixed(1), L::Unbounded, A::Any),
    ("crnumericsecond", R::Fixed(1), L::Unbounded, A::Any),
    ("crolive", R::Fixed(1), L::Unbounded, A::Any),
    ("croneandhalfpointline", R::Fixed(1), L::Unbounded, A::Any),
    ("croneorzero", R::Fixed(1), L::Unbounded, A::Any),
    ("cronepointline", R::Fixed(1), L::Unbounded, A::Any),
    ("croriginalorder", R::Fixed(1), L::Unbounded, A::Any),
    ("crpi", R::Fixed(1), L::Unbounded, A::Exact(0)),
    ("crportrait", R::Fixed(1), L::Unbounded, A::Any),
    ("crpurple", R::Fixed(1), L::Unbounded, A::Any),
    ("crred", R::Fixed(1), L::Unbounded, A::Any),
    ("crregular", R::Fixed(1), L::Unbounded, A::Any),
    ("crrightaligned", R::Fixed(1), L::Unbounded, A::Any),
    ("crrighttolefttextreadingorder", R::Fixed(1), L::Unbounded, A::Any),
    ("crrtftext", R::Fixed(1), L::Unbounded, A::Any),
    ("crsaturday", R::Fixed(1), L::Unbounded, A::Any),
    ("crshortdayofweek", R::Fixed(1), L::Unbounded, A::Any),
    ("crshortera", R::Fixed(1), L::Unbounded, A::Any),
    ("crshortleadingday", R::Fixed(1), L::Unbounded, A::Any),
    ("crshortmonth", R::Fixed(1), L::Unbounded, A::Any),
    ("crshortyear", R::Fixed(1), L::Unbounded, A::Any),
    ("crsilver", R::Fixed(1), L::Unbounded, A::Any),
    ("crsingleline", R::Fixed(1), L::Unbounded, A::Any),
    ("crsunday", R::Fixed(1), L::Unbounded, A::Any),
    ("crteal", R::Fixed(1), L::Unbounded, A::Any),
    ("crthreeandhalfpointline", R::Fixed(1), L::Unbounded, A::Any),
    ("crthreepointline", R::Fixed(1), L::Unbounded, A::Any),
    ("crthursday", R::Fixed(1), L::Unbounded, A::Any),
    ("crtimeonly", R::Fixed(1), L::Unbounded, A::Any),
    ("crtimethendate", R::Fixed(1), L::Unbounded, A::Any),
    ("crtopaligned", R::Fixed(1), L::Unbounded, A::Any),
    ("crtorf", R::Fixed(1), L::Unbounded, A::Any),
    ("crtrailingcurrencyinsidenegative", R::Fixed(1), L::Unbounded, A::Any),
    ("crtrailingcurrencyoutsidenegative", R::Fixed(1), L::Unbounded, A::Any),
    ("crtrailingdayofweek", R::Fixed(1), L::Unbounded, A::Any),
    ("crtrailingminus", R::Fixed(1), L::Unbounded, A::Any),
    ("crtrueorfalse", R::Fixed(1), L::Unbounded, A::Any),
    ("crtuesday", R::Fixed(1), L::Unbounded, A::Any),
    ("crtwelvehour", R::Fixed(1), L::Unbounded, A::Any),
    ("crtwentyfourhour", R::Fixed(1), L::Unbounded, A::Any),
    ("crtwoandhalfpointline", R::Fixed(1), L::Unbounded, A::Any),
    ("crtwopointline", R::Fixed(1), L::Unbounded, A::Any),
    ("cruninterpretedtext", R::Fixed(1), L::Unbounded, A::Any),
    ("crusesystem", R::Fixed(1), L::Unbounded, A::Any),
    ("crwednesday", R::Fixed(1), L::Unbounded, A::Any),
    ("crwhite", R::Fixed(1), L::Unbounded, A::Any),
    ("crwindowslong", R::Fixed(1), L::Unbounded, A::Any),
    ("crwindowsshort", R::Fixed(1), L::Unbounded, A::Any),
    ("cryearmonthday", R::Fixed(1), L::Unbounded, A::Any),
    ("cryellow", R::Fixed(1), L::Unbounded, A::Any),
    ("cryesorno", R::Fixed(1), L::Unbounded, A::Any),
    ("cryorn", R::Fixed(1), L::Unbounded, A::Any),
    ("cstr", R::Fixed(7), L::Coerce, A::Range(1, 4)),
    ("ctime", R::Fixed(5), L::Unbounded, A::Range(1, 3)),
    ("cumipmt", R::Fixed(1), L::Unbounded, A::Any),
    ("cumprinc", R::Fixed(1), L::Unbounded, A::Any),
    ("currentceuserid", R::Complex, L::Unbounded, A::Any),
    ("currentceusername", R::Complex, L::Unbounded, A::Any),
    ("currentceusertimezone", R::Complex, L::Unbounded, A::Any),
    ("currentcolumnindex", R::Fixed(1), L::Unbounded, A::Any),
    ("currentdate", R::Fixed(4), L::Unbounded, A::Any),
    ("currentdatetime", R::Fixed(6), L::Unbounded, A::Any),
    ("currentfieldvalue", R::Complex, L::Unbounded, A::Any),
    ("currentpageorientation", R::Complex, L::Unbounded, A::Any),
    ("currentrowindex", R::Fixed(1), L::Unbounded, A::Any),
    ("currentsummaryindex", R::Complex, L::Unbounded, A::Any),
    ("currenttime", R::Fixed(5), L::Unbounded, A::Any),
    ("datadate", R::Complex, L::Unbounded, A::Any),
    ("datatime", R::Complex, L::Unbounded, A::Any),
    ("datatimezone", R::Complex, L::Unbounded, A::Any),
    ("dateadd", R::Fixed(6), L::Unbounded, A::Exact(3)),
    ("datediff", R::Fixed(1), L::Unbounded, A::Range(3, 4)),
    ("datepart", R::Fixed(1), L::Unbounded, A::Range(2, 4)),
    ("dateserial", R::Fixed(4), L::Unbounded, A::Exact(3)),
    ("datetimevalue", R::Fixed(6), L::Unbounded, A::Range(1, 6)),
    ("datevalue", R::Fixed(4), L::Unbounded, A::Range(1, 3)),
    ("day", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("dayofweek", R::Fixed(1), L::Unbounded, A::Range(1, 2)),
    ("days360", R::Fixed(1), L::Unbounded, A::Any),
    ("db", R::Fixed(1), L::Unbounded, A::Any),
    ("ddb", R::Fixed(1), L::Unbounded, A::Range(4, 5)),
    ("defaultattribute", R::Complex, L::Unbounded, A::Any),
    ("disc", R::Fixed(1), L::Unbounded, A::Any),
    ("distinctcount", R::Fixed(1), L::Unbounded, A::Any),
    ("dollarde", R::Fixed(1), L::Unbounded, A::Any),
    ("dollarfr", R::Fixed(1), L::Unbounded, A::Any),
    ("drilldowngrouplevel", R::Fixed(1), L::Unbounded, A::Any),
    ("duration", R::Fixed(1), L::Unbounded, A::Any),
    ("effect", R::Fixed(1), L::Unbounded, A::Any),
    ("evaluateafter", R::Fixed(1), L::Unbounded, A::Any),
    ("exp", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("fileauthor", R::Complex, L::Unbounded, A::Any),
    ("filecreationdate", R::Complex, L::Unbounded, A::Any),
    ("filename", R::Complex, L::Unbounded, A::Any),
    ("filter", R::Fixed(21), L::CopyArg1, A::Range(2, 4)),
    ("fix", R::CopyArg, L::Unbounded, A::Range(1, 2)),
    ("floor", R::CopyArg, L::Unbounded, A::Range(1, 2)),
    ("fv", R::Fixed(1), L::Unbounded, A::Range(3, 5)),
    ("fvschedule", R::Fixed(1), L::Unbounded, A::Any),
    ("getcolumngroupindexof", R::Fixed(1), L::Unbounded, A::Any),
    ("getcolumnpathindexof", R::Fixed(1), L::Unbounded, A::Any),
    ("getindexof", R::Fixed(1), L::Unbounded, A::Any),
    ("getlowerbound", R::DeArray, L::Coerce, A::Any),
    ("getnumcolumngroups", R::Complex, L::Unbounded, A::Any),
    ("getnumcolumns", R::Fixed(1), L::Unbounded, A::Any),
    ("getnumrowgroups", R::Complex, L::Unbounded, A::Any),
    ("getnumrows", R::Fixed(1), L::Unbounded, A::Any),
    ("getnumsummaries", R::Fixed(1), L::Unbounded, A::Any),
    ("getrowgroupindexof", R::Fixed(1), L::Unbounded, A::Any),
    ("getrowpathindexof", R::Fixed(1), L::Unbounded, A::Any),
    ("gettotalvaluefor", R::Complex, L::Unbounded, A::Any),
    ("getupperbound", R::Complex, L::Coerce, A::Any),
    ("getvaluedescriptions", R::Complex, L::Coerce, A::Any),
    ("gridlabelat", R::Complex, L::Unbounded, A::Any),
    ("gridrowcolumnvalue", R::Complex, L::Unbounded, A::Any),
    ("gridvalueat", R::Complex, L::Unbounded, A::Any),
    ("groupinglevel", R::Complex, L::Unbounded, A::Any),
    ("groupname", R::Complex, L::Unbounded, A::Any),
    ("groupnumber", R::Complex, L::Unbounded, A::Any),
    ("groupselection", R::Complex, L::Unbounded, A::Any),
    ("haslowerbound", R::Fixed(3), L::Unbounded, A::Any),
    ("hasupperbound", R::Fixed(3), L::Unbounded, A::Any),
    ("hasvalue", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("hierarchylevel", R::Fixed(1), L::Unbounded, A::Any),
    ("hour", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("iif", R::Iif, L::BranchMax, A::Exact(3)),
    ("includeslowerbound", R::Complex, L::Unbounded, A::Any),
    ("includesupperbound", R::Complex, L::Unbounded, A::Any),
    ("inrepeatedgroupheader", R::Fixed(3), L::Unbounded, A::Any),
    ("instr", R::Fixed(1), L::Unbounded, A::Range(2, 3)),
    ("instrrev", R::Fixed(1), L::Unbounded, A::Range(2, 3)),
    ("int", R::CopyArg, L::Unbounded, A::Exact(1)),
    ("intrate", R::Fixed(1), L::Unbounded, A::Any),
    ("ipmt", R::Fixed(1), L::Unbounded, A::Any),
    ("irr", R::Fixed(1), L::Unbounded, A::Range(1, 2)),
    ("isalertenabled", R::Complex, L::Unbounded, A::Any),
    ("isalerttriggered", R::Complex, L::Unbounded, A::Any),
    ("isbusinessday", R::Complex, L::Unbounded, A::Any),
    ("isdate", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("isdatetime", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("isnull", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("isnumeric", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("ispmt", R::Fixed(1), L::Unbounded, A::Any),
    ("istime", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("join", R::Fixed(7), L::Unbounded, A::Range(1, 2)),
    ("last4weekstosun", R::Fixed(11), L::Unbounded, A::Any),
    ("last7days", R::Fixed(11), L::Unbounded, A::Any),
    ("lastfullmonth", R::Fixed(11), L::Unbounded, A::Any),
    ("lastfullweek", R::Fixed(11), L::Unbounded, A::Any),
    ("lastyearmtd", R::Fixed(11), L::Unbounded, A::Any),
    ("lastyearytd", R::Fixed(11), L::Unbounded, A::Any),
    ("lcase", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("left", R::Fixed(7), L::ArgTimes4, A::Exact(2)),
    ("len", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("length", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("log", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("lowercase", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("ltrim", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("makearray", R::Complex, L::Unbounded, A::Any),
    ("maximum", R::MaxMinArg, L::Unbounded, A::AtLeast(1)),
    ("mduration", R::Fixed(1), L::Unbounded, A::Any),
    ("median", R::Complex, L::Unbounded, A::Any),
    ("mid", R::Fixed(7), L::Unbounded, A::Range(2, 3)),
    ("minimum", R::MaxMinArg, L::Unbounded, A::AtLeast(1)),
    ("minute", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("mirr", R::Fixed(1), L::Unbounded, A::Any),
    ("mode", R::Complex, L::Unbounded, A::Any),
    ("modificationdate", R::Complex, L::Unbounded, A::Any),
    ("modificationtime", R::Complex, L::Unbounded, A::Any),
    ("month", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("monthname", R::Fixed(7), L::Const(100), A::Range(1, 2)),
    ("monthtodate", R::Fixed(11), L::Unbounded, A::Any),
    ("mround", R::CopyArg, L::Unbounded, A::Exact(2)),
    ("next30days", R::Fixed(11), L::Unbounded, A::Any),
    ("next31to60days", R::Fixed(11), L::Unbounded, A::Any),
    ("next61to90days", R::Fixed(11), L::Unbounded, A::Any),
    ("next91to365days", R::Fixed(11), L::Unbounded, A::Any),
    ("nextisnull", R::Fixed(3), L::Unbounded, A::Any),
    ("nextnbusinessdays", R::Complex, L::Unbounded, A::Any),
    ("nominal", R::Fixed(1), L::Unbounded, A::Any),
    ("nper", R::Fixed(1), L::Unbounded, A::Any),
    ("npv", R::Fixed(1), L::Unbounded, A::AtLeast(2)),
    ("nthlargest", R::Complex, L::Unbounded, A::Any),
    ("nthmostfrequent", R::Complex, L::Unbounded, A::Any),
    ("nthsmallest", R::Complex, L::Unbounded, A::Any),
    ("numerictext", R::Fixed(3), L::Unbounded, A::Exact(1)),
    ("oddfprice", R::Fixed(1), L::Unbounded, A::Any),
    ("oddfyield", R::Fixed(1), L::Unbounded, A::Any),
    ("oddlprice", R::Fixed(1), L::Unbounded, A::Any),
    ("oddlyield", R::Fixed(1), L::Unbounded, A::Any),
    ("onfirstrecord", R::Fixed(3), L::Unbounded, A::Any),
    ("onlastrecord", R::Fixed(3), L::Unbounded, A::Any),
    ("over90days", R::Fixed(11), L::Unbounded, A::Any),
    ("pagenofm", R::Complex, L::Unbounded, A::Any),
    ("pagenumber", R::Complex, L::Unbounded, A::Any),
    ("percentofaverage", R::Complex, L::Unbounded, A::Any),
    ("percentofcount", R::Complex, L::Unbounded, A::Any),
    ("percentofdistinctcount", R::Complex, L::Unbounded, A::Any),
    ("percentofmaximum", R::Complex, L::Unbounded, A::Any),
    ("percentofminimum", R::Complex, L::Unbounded, A::Any),
    ("percentofsum", R::Complex, L::Unbounded, A::Any),
    ("pmt", R::Fixed(1), L::Unbounded, A::Range(3, 5)),
    ("populationstddev", R::AggNumeric, L::Unbounded, A::AtLeast(1)),
    ("populationvariance", R::Fixed(1), L::Unbounded, A::AtLeast(1)),
    ("ppmt", R::Fixed(1), L::Unbounded, A::Any),
    ("previousisnull", R::Fixed(3), L::Unbounded, A::Any),
    ("price", R::Fixed(1), L::Unbounded, A::Any),
    ("pricedisc", R::Fixed(1), L::Unbounded, A::Any),
    ("pricemat", R::Fixed(1), L::Unbounded, A::Any),
    ("printdate", R::Fixed(4), L::Unbounded, A::Any),
    ("printtime", R::Fixed(5), L::Unbounded, A::Any),
    ("printtimezone", R::Complex, L::Unbounded, A::Any),
    ("propercase", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("pthpercentile", R::Complex, L::Unbounded, A::Any),
    ("pv", R::Fixed(1), L::Unbounded, A::Range(3, 5)),
    ("rate", R::Fixed(1), L::Unbounded, A::Range(3, 6)),
    ("received", R::Fixed(1), L::Unbounded, A::Any),
    ("recordnumber", R::Complex, L::Unbounded, A::Any),
    ("recordselection", R::Complex, L::Unbounded, A::Any),
    ("remainder", R::Complex, L::Unbounded, A::Exact(2)),
    ("replace", R::Fixed(7), L::Unbounded, A::Exact(3)),
    ("replicatestring", R::Fixed(7), L::ReplicateRule, A::Exact(2)),
    ("reportcomments", R::Complex, L::Unbounded, A::Any),
    ("reporttitle", R::Complex, L::Unbounded, A::Any),
    ("rgb", R::Fixed(1), L::Unbounded, A::Exact(3)),
    ("right", R::Fixed(7), L::ArgTimes4, A::Exact(2)),
    ("rnd", R::Fixed(1), L::Unbounded, A::Any),
    ("roman", R::Fixed(7), L::Const(32), A::Range(1, 2)),
    ("round", R::CopyArg, L::Unbounded, A::Range(1, 2)),
    ("roundup", R::CopyArg, L::Unbounded, A::Range(1, 2)),
    ("rtrim", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("second", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("selectionlocale", R::Complex, L::Unbounded, A::Any),
    ("sgn", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("shiftdatetime", R::Fixed(6), L::Unbounded, A::Any),
    ("sin", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("sln", R::Fixed(1), L::Unbounded, A::Exact(3)),
    ("space", R::Fixed(7), L::SpaceRule, A::Exact(1)),
    ("split", R::Fixed(21), L::CopyArg1, A::Range(1, 4)),
    ("sqr", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("stddev", R::AggNumeric, L::Unbounded, A::AtLeast(1)),
    ("strcmp", R::Fixed(1), L::Unbounded, A::Range(2, 3)),
    ("strreverse", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("sum", R::AggNumeric, L::Unbounded, A::AtLeast(1)),
    ("switch", R::Switch, L::BranchMax, A::EvenAtLeast(2)),
    ("syd", R::Fixed(1), L::Unbounded, A::Exact(4)),
    ("tan", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("tbilleq", R::Fixed(1), L::Unbounded, A::Any),
    ("tbillprice", R::Fixed(1), L::Unbounded, A::Any),
    ("tbillyield", R::Fixed(1), L::Unbounded, A::Any),
    ("timer", R::Fixed(1), L::Unbounded, A::Any),
    ("timeserial", R::Fixed(5), L::Unbounded, A::Exact(3)),
    ("timevalue", R::Fixed(5), L::Unbounded, A::Range(1, 3)),
    ("today", R::Fixed(4), L::Unbounded, A::Any),
    ("tonumber", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("totalpagecount", R::Complex, L::Unbounded, A::Any),
    ("totext", R::Fixed(7), L::Coerce, A::Range(1, 4)),
    ("towords", R::Fixed(7), L::Const(1400), A::Range(1, 2)),
    ("toxmlcolumn", R::Fixed(7), L::Unbounded, A::Any),
    ("toxmldata", R::Fixed(7), L::Unbounded, A::Any),
    ("toxmlrow", R::Fixed(7), L::Unbounded, A::Any),
    ("trim", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("trimleft", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("trimright", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("truncate", R::CopyArg, L::Unbounded, A::Range(1, 2)),
    ("ubound", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("ucase", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("uppercase", R::Fixed(7), L::CopyArg1, A::Exact(1)),
    ("urldecode", R::Fixed(7), L::CopyArg1, A::Any),
    ("urlencode", R::Fixed(7), L::Unbounded, A::Any),
    ("val", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("variance", R::Fixed(1), L::Unbounded, A::AtLeast(1)),
    ("vdb", R::Fixed(1), L::Unbounded, A::Any),
    ("weekday", R::Fixed(1), L::Unbounded, A::Range(1, 2)),
    ("weekdayname", R::Fixed(7), L::Const(100), A::Range(1, 3)),
    ("weektodatefromsun", R::Fixed(11), L::Unbounded, A::Any),
    ("weightedaverage", R::Complex, L::Unbounded, A::Any),
    ("whileprintingrecords", R::Fixed(1), L::Unbounded, A::Any),
    ("whilereadingrecords", R::Fixed(1), L::Unbounded, A::Any),
    ("xirr", R::Fixed(1), L::Unbounded, A::Any),
    ("xnpv", R::Fixed(1), L::Unbounded, A::Any),
    ("year", R::Fixed(1), L::Unbounded, A::Exact(1)),
    ("yearfrac", R::Fixed(1), L::Unbounded, A::Any),
    ("yeartodate", R::Fixed(11), L::Unbounded, A::Any),
    ("yield", R::Fixed(1), L::Unbounded, A::Any),
    ("yielddisc", R::Fixed(1), L::Unbounded, A::Any),
    ("yieldmat", R::Fixed(1), L::Unbounded, A::Any),
];
